version: 2.1
jobs:
  build-node14:
    docker:
      - image: circleci/node:14-browsers
    working_directory: ~/repo
    steps:
      - run: sudo apt-get install libxss1
      - checkout

workflows:
  version: 2
  voter:
    jobs:
      - build-node14
